import Vapor

/// Response structure for OpenAI-compatible chat completions endpoint
struct ChatCompletionResponse: Content {
    /// Unique identifier for this completion
    let id: String

    /// Object type (always "chat.completion")
    let object: String

    /// Unix timestamp of when the completion was created
    let created: Int

    /// The model used for completion
    let model: String

    /// List of completion choices
    let choices: [Choice]

    /// A completion choice returned by the model
    struct Choice: Codable {
        /// Index of this choice in the list
        let index: Int

        /// The message generated by the model
        let message: ChatMessage

        /// Reason the model stopped generating tokens
        let finishReason: String?

        enum CodingKeys: String, CodingKey {
            case index
            case message
            case finishReason = "finish_reason"
        }
    }
}
